// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt3wyZSBfGUfzq7i-Lv9M2pd9nFd08dU0',
    appId: '1:736737602796:web:07cc14bfcaf7ff184c89c9',
    messagingSenderId: '736737602796',
    projectId: 'smart-bio-floc-4150e',
    authDomain: 'smart-bio-floc-4150e.firebaseapp.com',
    databaseURL: 'https://smart-bio-floc-4150e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-bio-floc-4150e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmQLw4HBPTAL-xaH6LqYT52KAKwyZMupM',
    appId: '1:736737602796:android:3bc60ea6e3eb716b4c89c9',
    messagingSenderId: '736737602796',
    projectId: 'smart-bio-floc-4150e',
    databaseURL: 'https://smart-bio-floc-4150e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-bio-floc-4150e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbtL8JY0QgacA2Q2Jk-Cw112mynx7so6o',
    appId: '1:736737602796:ios:239c1c9695fdebbc4c89c9',
    messagingSenderId: '736737602796',
    projectId: 'smart-bio-floc-4150e',
    databaseURL: 'https://smart-bio-floc-4150e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-bio-floc-4150e.appspot.com',
    iosBundleId: 'com.example.smartbiofloc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbtL8JY0QgacA2Q2Jk-Cw112mynx7so6o',
    appId: '1:736737602796:ios:0a9c848490ebc1e34c89c9',
    messagingSenderId: '736737602796',
    projectId: 'smart-bio-floc-4150e',
    databaseURL: 'https://smart-bio-floc-4150e-default-rtdb.firebaseio.com',
    storageBucket: 'smart-bio-floc-4150e.appspot.com',
    iosBundleId: 'com.example.smartbiofloc.RunnerTests',
  );
}
